version: 2
jobs:
    build:
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - restore_cache: # special step to restore the dependency cache
            # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
            keys: 
              - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
              - v2-deps-{{ .Branch }}-
              - v2-deps-
        - save_cache:
            key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            paths:
              - ~/.npm
              - ~/.cache
        - run:
            name: install NPM Packages
            command: npm ci
        - setup_remote_docker:   
            docker_layer_caching: true 
        - run:
            name: Spin up Docker Image
            command: docker-compose build
        - run:
            name: Start Docker Image
            command: docker-compose up --exit-code-from cypress
        - store_artifacts:
            path: ./tests/cypress/videos
            
