version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
      - image: cypress/base:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
           ## - ~/.npm
            - ~/.cache
      - run:
          name: install NPM Packages
          command: npm ci
      - run: npm run cy:verify
      ##- save_cache:
      ##    key: dependency-cache-{{ checksum "package.json" }}
      ##    paths:
      ##      - ./node_modules
      - setup_remote_docker:   
          docker_layer_caching: true 
      - persist_to_workspace:
          root: ~/
          paths:
             - .cache/Cypress
      - run:
          name: Spin up Docker Image
          command: docker-compose build
      - run:
          name: Start Docker Image
          command: docker-compose up
          background: true
       
      #- run:
      #    name: Wait for Service
      #    command: npm run wait-on
      - attach_workspace:
          at: ~/
      - run:
          name: Run Cypress Tests
          command: npm run test
      - run:
          name: Kill Server
          command: docker-compose down --volumes
      - store_artifacts:
          path: .\cypress\videos
          prefix: videos
